apiVersion: v1
kind: PersistentVolume
metadata:
  name: hwk8s-local-pv
  namespace: hwk8s-ns
spec:
  capacity:
    storage: 1Gi 
  hostPath: #укажем путь до локальной папки
    path: >-
      /media/akozlov/06b9b68a-882f-4f94-ad63-4c9e75de88f35/projects/hwandk8s/hwk8s-volume
    type: DirectoryOrCreate #если нет папки то создадим
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem    
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hwk8s-local-pvc
  namespace: hwk8s-ns
spec:
  storageClassName: local-storage
  volumeName: hwk8s-local-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi