apiVersion: v1
kind: Service
metadata:
  name: f8ks-gogo-s
  namespace: hwk8s-ns
spec:
  type: NodePort
  selector:
    app: hwk8s-gogo-ms
  ports:
    - port: 8080
      nodePort: 30055 #для внешнего подключения
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwk8s-gogo-dep-ms
  namespace: hwk8s-ns
  labels:
    app: hwk8s-gogo-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwk8s-gogo-ms
  template:
    metadata:
      labels:
        app: hwk8s-gogo-ms
    spec:
      containers:
        - name: hwk8s-gogo-ms-pod
          image: localhost:5000/my-gogo-app_v1
          ports:
          - containerPort: 8080
