apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwk8s-nginx-dep
  namespace: hwk8s-ns
  labels:
    app: hwk8s-nginx
spec:
  replicas: 2
  #это необязательное поле, которое определяет селектор меток для подов, предназначенных для этого развертывания.
  #В таком случае, .spec.selector должен соответствовать значению .spec.template.metadata.labels
  selector:
    matchLabels:
      app: hwk8s-nginx
  template:
    metadata:
      labels:
        app: hwk8s-nginx
    spec:
      containers:
        - name: hwk8s-nginx-pod
          image: nginx:alpine
          ports:
          - protocol: TCP
            containerPort: 80