apiVersion: v1
kind: Service
metadata:
  name: hwk8s-ns-s
  namespace: hwk8s-ns
spec:
  type: NodePort
  selector:
    app: hwk8s-nginx # название пода nginx 
  ports:
  - name: http
    protocol: TCP
    port: 80 # на этом порту работает под nginx
    nodePort: 30050
