apiVersion: v1
kind: PersistentVolume
metadata:
  name: hwk8s-db-pv
  namespace: hwk8s-ns
spec:
  capacity:
    storage: 1Gi 
  hostPath: #укажем путь до локальной папки
    path: >-
      /media/akozlov/06b9b68a-882f-4f94-ad63-4c9e75de88f35/projects/hwandk8s/db
    type: DirectoryOrCreate #если нет папки то создадим
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem    
  storageClassName: local-storage  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hwk8s-db-pvc
  namespace: hwk8s-ns
spec:
  storageClassName: local-storage
  volumeName: hwk8s-db-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: hwk8s-db-s
  namespace: hwk8s-ns
spec:
  type: NodePort
  selector:
    app: hwk8s-db
  ports:
    - port: 5432
      nodePort: 30051 #для внешнего подключения
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwk8s-db-dep
  namespace: hwk8s-ns
  labels:
    app: hwk8s-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwk8s-db
  template:
    metadata:
      labels:
        app: hwk8s-db
    spec:
      volumes:
        - name: hwk8s-db-pvc-v
          persistentVolumeClaim:
            claimName: hwk8s-db-pvc
      containers:
        - name: hwk8s-db-pod
          image: postgres:latest
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "test"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "qwerty"
          volumeMounts:
            - name: hwk8s-db-pvc-v
              mountPath: /var/lib/postgresql/data
